version: "3.4"

# 이미지와 네트워크 정보에 대한 base service를 지정
x-datanode_base: &datanode_base
  image: hadoop-datanode:3.3.0
  networks:
    - bridge
  depends_on:
    - namenode

services:
  namenode:
    image: hadoop-namenode:3.3.0
    container_name: namenode
    hostname: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - namenode:/opt/spark/eventLog
      - namenode:/opt/hadoop/yarn/timeline
      - /tmp:/tmp
    networks:
      - bridge

  resource-manager:
    image: hadoop-resource-manager:3.3.0
    container_name: resource-manager
    hostname: resource-manager
    ports:
      - 8088:8088
    volumes:
      - /tmp:/tmp
    networks:
      - bridge

  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
  
  datanode02:
    <<: *datanode_base
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/opt/hadoop/dfs/data

  datanode03:
    <<: *datanode_base
    container_name: datanode03
    hostname: datanode03
    volumes:
      - datanode03:/opt/hadoop/dfs/data
  
  yarn-timeline-server:
    image: yarn-timeline-server:3.3.0
    container_name: yarn-timeline-server
    hostname: yarn-timeline-server
    ports:
      - 8188:8188
    volumes:
      - namenode:/opt/hadoop/yarn/timeline
    networks:
      - bridge

  hive-metastore-mysql:
    image: mysql:8
    container_name: hive-metastore-mysql
    hostname: hive-metastore-mysql
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    networks:
      - bridge
    volumes:
      - metastore:/var/lib/mysql

  hive-server:
    image: hive-image:3.1.2
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - resource-manager
      - yarn-timeline-server
      - hive-metastore
    volumes:
      - ./dummy_data:/opt/dummy_data
    env_file:
      - hive.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - bridge

  hive-metastore:
    image: hive-image:3.1.2
    container_name: hive-metastore
    hostname: hive-metastore
    depends_on:
      - hive-metastore-mysql
    env_file:
      - hive.env
    command: [ "startup.sh", "metastore" ]
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode01:9864 datanode02:9864 datanode03:9864 hive-metastore-mysql:3306"
    ports:
      - "9083:9083"
    networks:
      - bridge
  
  spark-history-server:
    image: spark-history-server:3.3.1
    container_name: spark-history-server
    hostname: spark-history-server
    ports:
      - "9093:18080"
    depends_on:
      - namenode
      - resource-manager
    volumes:
      - namenode:/opt/spark/eventLog
    networks:
      - bridge
  
  zeppelin:
    image: zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin
    ports:
      - "9097:8080"
    networks:
      - bridge
    volumes:
      - namenode:/opt/spark/eventLog
      - ./notebook:/zeppelin-0.10.1-bin-all/notebook

volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:
  metastore:

networks:
  bridge: